---

- name: RHEL7 Swap repo to nexcess
  hosts: containerhost
  become: true
  tasks:
    - shell: 'sed -i -e "s/mirrorlist/#mirrorlist/" -e "s/#baseurl/baseurl/" -e "s/mirror.centos.org\/centos\//mirror.us-midwest-1.nexcess.net\/CentOS\//" /etc/yum.repos.d/CentOS-Base.repo'
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '7'

- name: RHEL7 PIP use openSSL bundle instead of Pythons
  hosts: containerhost
  become: true
  tasks:
    - copy:
      dest: "/etc/pip.conf"
      content: |
        [global]
        cert = /etc/ssl/certs/ca-bundle.crt
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '7'

- include: base.yml

- name: Setup a ContainerHost
  hosts: containerhost
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include: tasks/containerhost.yml mode="pre"
  roles:
    - nexcess.repo
    - nexcess.docker
    - { role: nexcess.puppet, when: "nex_env_target is undefined or nex_env_target != 'vagrant'" }
    - nexcess.elrepo
  post_tasks:
    - include: tasks/containerhost.yml mode="post"
